# Generated by Django 4.2.5 on 2023-09-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_rename_encrypted_password_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default='2023-09-19')),
                ('status', models.CharField(default='PROCESSING', max_length=32)),
                ('products', models.ManyToManyField(blank=True, db_constraint=False, to='products.product')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
