version: "3.11"

services:
  db:
    image: postgres:latest
    container_name: shop_postgres_db
    restart: always
    volumes:
      - '/postgres_data:/var/lib/postgresql'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_ROOT_PASSWORD=1234'
      - 'POSTGRES_DB=test_case_shop'
      - 'PGDATA=/var/lib/postgresql/data'
    ports:
      - "5432:5432"
  backend:
    container_name: django_backend
    build: .
    command: bash -c 'python manage.py migrate && python manage.py loaddata data.json && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db