version: "3.11"

services:
  database:
    ports:
      - '5432:5432'
    image: postgres:latest
    container_name: shop-postgres-db
    volumes:
      - '/postgres_data:/var/lib/postgresql'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_DB=test_case_shop'
      - 'PGDATA=/var/lib/postgresql/data'
  backend:
    container_name: django_backend
    build: .
    command: bash -c 'pip install -r requirements.txt
                      && python manage.py makemigrations
                      && python manage.py migrate
                      && python manage.py runserver 0.0.0.0:8080'
    ports:
      - '8080:8080'
    depends_on:
      - database
