# Generated by Django 4.2.5 on 2023-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_products_alter_cart_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('products', 'user'), name='unique FKs in cart'),
        ),
    ]
