# Generated by Django 4.2.5 on 2023-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('birthday', models.DateField(default='2000-01-01')),
                ('email', models.EmailField(default='test@test.ru', max_length=255)),
                ('encrypted_password', models.CharField(default='1234', max_length=255)),
            ],
        ),
    ]
