# Generated by Django 4.2.5 on 2023-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@test.ru', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='encrypted_password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=16),
        ),
    ]
